server:
  addr: ":8080"
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 120s

postgres:
  host: localhost
  port: 5432
  user: admin
  password: admin
  dbname: comment-tree
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 5
  max_conn_lifetime: 1h

logger:
  level: debug
  format: console